//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.15 at 04:38:39 PM AST 
//


package by.iba.railway.eticket.xml.objs.response.type.G11;

import by.iba.railway.eticket.xml.objs.response.express.interfaces.Train;
import by.iba.railway.eticket.xml.objs.response.type.common.ArrivalType;
import by.iba.railway.eticket.xml.objs.response.type.common.DepartureType;
import by.iba.railway.eticket.xml.objs.response.type.common.RouteType;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainType", propOrder = {
    "storageIC",
    "route",
    "departure",
    "arrival",
    "timeInWay",
    "daysOfGo",
    "distance",
    "firm"
})
public class TrainG11Type implements Train{
    @XmlElement(name = "StorageIC")
    protected String storageIC;
    @XmlElement(name = "Route", required = true)
    protected RouteType route;
    @XmlElement(name = "Departure", required = true)
    protected DepartureType departure;
    @XmlElement(name = "Arrival", required = true)
    protected ArrivalType arrival;
    @XmlElement(name = "TimeInWay", required = true)
    protected String timeInWay;
    @XmlElement(name = "DaysOfGo", required = true)
    protected String daysOfGo;
    @XmlElement(name = "Distance")
    protected Integer distance;
    @XmlElement(name = "Firm", required = true)
    protected String firm;
    @XmlAttribute(name = "Number")
    protected String number;
    @XmlAttribute(name = "Number2")
    protected String number2;
    @XmlAttribute(name = "Number3")
    protected String number3;

    public RouteType getRoute() {
        return route;
    }

    public void setRoute(RouteType value) {
        this.route = value;
    }

    public DepartureType getDeparture() {
        return departure;
    }

    public void setDeparture(DepartureType value) {
        this.departure = value;
    }

    public ArrivalType getArrival() {
        return arrival;
    }

    public void setArrival(ArrivalType value) {
        this.arrival = value;
    }

    public String getTimeInWay() {
        return timeInWay;
    }

    public void setTimeInWay(String value) {
        this.timeInWay = value;
    }

    public String getDaysOfGo() {
        return daysOfGo;
    }

    public void setDaysOfGo(String value) {
        this.daysOfGo = value;
    }

    public Integer getDistance() {
        return distance;
    }

    public void setDistance(Integer value) {
        this.distance = value;
    }

    public String getFirm() {
        return firm;
    }

    public void setFirm(String value) {
        this.firm = value;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String value) {
        this.number = value;
    }

    public String getNumber2() {
        return number2;
    }

    public void setNumber2(String number2) {
        this.number2 = number2;
    }

    public String getNumber3() {
        return number3;
    }

    public void setNumber3(String number3) {
        this.number3 = number3;
    }

    public String getStorageIC() {
        return storageIC;
    }

    public void setStorageIC(String storageIC) {
        this.storageIC = storageIC;
    }
}
